CREATE DATABASE college;
use college;

CREATE TABLE STUDENT(
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT NOT NULL
);

INSERT INTO STUDENT(ROLLNO,NAME,AGE) VALUES (101,"KIRAN",27),(102,"SAI",23),(103,"ESWAR",25);


-- * MEANS ALL
SELECT * FROM STUDENT;
USE COLLEGE;
CREATE TABLE TEMP1(
    ID INT UNIQUE -- WE USING UNIQUE constraint

);
INSERT INTO TEMP1 VALUES (101);


-- DUPLICATE ENTRY it returns error
INSERT INTO TEMP1 VALUES (101);

SELECT * FROM TEMP1;
